//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAssignmentDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMasterInventoryID
    {
        public int ItemMasterInventoryID_PK { get; set; }
        public Nullable<decimal> IMIQtyOnHand { get; set; }
        public Nullable<decimal> IMIQtyAllocated { get; set; }
        public Nullable<int> ItemLocationID_FK { get; set; }
        public Nullable<int> IMIItemMasterID_FK { get; set; }
    }
}
